-- PERSON

INSERT INTO 
    person(Name, Surname, Gender, DoB, Email, Passwd, Phone, City, Description) 
VALUES 
    ("Xianwen", "Jin", "M", "1995-02-28", "jinxw@live.it", SHA2("Jinxw95",256), "3333333336", "Antananarivo", "<h1>Lezioni di Database - Laureato a pieni voti con 10 anni di esperienza</h1><h2>Metodologia</h2><p><br></p><p>Mi trovo sempre molto bene con i ragazzi e le ragazze che seguo.</p><p>Parto con una prima lezione in cui insieme andiamo a capire quali sono gli obiettivi del percorso.</p><p>Per poi seguire con una prima parte teorica per mettere le basi.</p><p>Chiudendo con tanta tanta pratica, sono piu' che convinto che per imparare bisogna fare.</p><p>Sono sempre disponibile anche fuori lezione per chiarire eventuali dubbi e per rispondere a curiosita'&nbsp; e domande.</p><p><br></p><h2>Ambasciatore</h2><p><br></p><p>e' il meglio del meglio degli insegnanti. Qualita'&nbsp; del profilo, diplomi e certificati di ottimo livello, risposta rapida. Xianwen prepara&nbsp; con cura la prima lezione.</p><p><br></p><h2>Percorso</h2><p><br></p><p>La regola e' dare ai ragazzi un obbiettivo e spiegare il perche' si stanno imparando queste cose.</p><h2>Tariffe</h2><p>Tariffa per lezioni via webcam :&nbsp;<strong>35euro/ora</strong></p><p><u>Tariffa per un pacchetto di 5 ore di lezioni :&nbsp;</u><strong>150euro</strong></p><p><u>Tariffa per un pacchetto di 10 ore di lezioni :&nbsp;</u><strong>315euro</strong></p><p><br></p><h2><strong>Curriculum Vitae</strong></h2><p><br></p><p>Laureato in informatica a pieni voti a Padova</p><p><br></p><p><br></p>"),
    
    ("Marco", "Grande", "M", "1996-02-10", "guess@live.it", SHA2("WantPass123",256), "345678910", "Padua", "<h1>Laureando in ingegneria Informatica a Padova propone lezioni di Programmazione e informatica online o di persona</h1><h2>Metodologia</h2><p>Sono uno studente di ingegneria all'universita'&nbsp; degli studi di Padova. Possiedo una laurea triennale in ingegneria dell'Informazione e attualmente frequento la laurea magistrale di Ingegneria Informatica.</p><p><br></p><p>Ho sempre dato ripetizioni di matematica e informatica alla vecchia maniera (di persona e tramite annunci in bacheca) e ora intraprendo questo nuovo percorso di e-learning in quanto credo molto nell'efficacia delle lezioni online.</p><p><br></p><p>Offro ripetizioni di Programmazione e informatica per molti linguaggi di programmazione come C, C++, Java, HTML, CSS, Javascript, jQuery, PHP, Python e altri, con particolare attenzione ad aspetti come algoritmi ed efficienza.</p><p><br></p><p>Inoltre, offro anche ripetizioni di Matematica per tutti i livelli.</p><h2>Percorso</h2><p>Il mio approccio e' molto pragmatico, mi piace far capire i concetti tramite esempi o, ancora meglio, esercizi pratici/rappresentazioni grafiche.</p><p><br></p><p>Imparare solo a memoria le cose non e' il mio stile, preferisco condurre lo studente alla soluzione tramite percorsi logici, che gli permettano di capire davvero cosa c'e' dietro le metodologie ed assimilare a pieno le nozioni. Mi piace quindi far capire, invece che far memorizzare a pappagallo.</p><p><br></p><p>Questo, oltre a motivare e appassionare, prepara a tutte le possibili \"anomalie\" di un possibile compito scolastico o universitario, dovute all'intrinseca variabilita'&nbsp; della Matematica e dell'Informatica.</p><p><br></p><p>Sono una persona molto seria ma anche molto alla mano, mi piace mettere a proprio agio gli studenti e prediligo un ambiente informale.</p><h2><span style=\"background-color: rgb(247, 247, 247); color: rgb(68, 68, 68);\">&nbsp;</span>Tariffe</h2><p>Tariffa per lezioni via webcam :&nbsp;<strong>15euro/ora</strong></p><h2>Precisazioni</h2><p>Gradito un preavviso in caso di annullamento di almeno 24/48h</p><h2><span style=\"background-color: rgb(247, 247, 247); color: rgb(68, 68, 68);\">&nbsp;</span><strong>Curriculum Vitae</strong>&nbsp;di Marco</h2><p>Diploma di Scuola secondaria superiore presso Istituto Tecnico Industriale con voto 100/100</p><p>Laurea triennale in Ingegneria dell'Informazione presso l'universita'&nbsp; di Padova con voto 100/110</p><p>Ho dato ripetizioni di diverse materie, principalmente Matematica e Informatica</p><p>Ho esperienza di programmazione Web e da piattaforma con numerosi linguaggi di programmazione</p>"),
    
    ("Marco", "Piccolo", "M", "1995-11-28", "marco@live.it", SHA2("Guseee123",256), "3333332222", "MiVòaVòCiò", "<h1>Lezioni di programmazione Python per il machine learning, a Torino e online</h1><h2>Metodologia</h2><p>Le lezioni di \"Python per il machine learning\" hanno l'obiettivo di trasmettere agli studenti solide competenze per approcciarsi con successo alla programmazione in Python su progetti di machine learning. Il linguaggio Python verra'&nbsp; introdotto e spiegato facendo pratica direttamente su veri problemi di machine learning. Gli algoritmi saranno trattati nella loro interezza, partendo dall'acquisizione dei dati e dalle tecniche di pre-processing, fino alla valutazione e convalida dei risultati ottenuti.</p><p><br></p><p>Gli script in Python, gli esercizi con le soluzioni e tutto il materiale didattico saranno consegnati puntualmente alla fine di ogni lezione. Al termine del corso verra'&nbsp; rilasciato un certificato di frequenza con profitto. </p><p><br></p><p>Il programma:</p><p>- breve introduzione al paradigma della programmazione a oggetti e alla sintassi di Python</p><p><br></p><p>- acquisizione dei dati con la libreria Pandas</p><p><br></p><p>- lavorazione dei dati mancanti con le librerie Pandas e Numpy</p><p><br></p><p>- normalizzazione dei dati con Scikit-learn</p><p><br></p><p>- algoritmi per la selezione ed estrazione delle caratteristiche</p><p><br></p><p>- algoritmi di classificazione: Prinception, Regressione Logistica, SVM, alberi di decisioni, foreste casuali</p><p><br></p><p>- scelta degli iperparametri</p><p><br></p><p>- individuazione e risoluzione di problematiche di overfitting</p><p><br></p><p>- valutazione dei risultati ottenuti</p><h2>Ambasciatore</h2><p>E' il meglio del meglio degli insegnanti. Qualita'&nbsp; del profilo, diplomi e certificati di ottimo livello, risposta rapida. Marco preparera'&nbsp; con cura la prima lezione.</p><h2>Percorso</h2><p>Sono un docente di programmazione SQL, Python ed Excel con le seguenti certificazioni rilasciate dalla Microsoft:</p><p>Microsoft Certified Solution Expert: Data Management and Analytics</p><p>Microsoft Certified Solution Associate: SQL 2016 Database Development</p><p>Microsoft Certified Solution Associate: SQL Server 2012/2014</p><p><br></p><p>Ho un'esperienza di piu' di 400 ore di docenza presso aziende e privati.</p><h2>Tariffe</h2><p>Tariffa per lezioni via webcam :&nbsp;<strong>30euro/ora</strong></p>"), 
    
    ("Victor", "Semencenco", "M", "1993-04-20", "sexy@live.it", SHA2("Gondus123",256), "345678911", "Eden", "<h1>Ricercatore in Economia, ho vissuto negli Stati Uniti negli ultimi 3 anni. Offro ripetizioni di inglese (speaking, listening, writing and reading)</h1><h2>Metodologia</h2><p>Le lezioni sono fortemente basate sulle necessita' dello studente. A seconda delle sue preferenze e dei suoi desideri, possiamo lavorare intensamente ogni lezione su un aspetto diverso della lingua (comprensione orale, comprensione scritta, elaborazione orale) con l'impegno di svolgere un elaborato scritto nelle pause tra una lezione e l'altra che potra'&nbsp; essere corretto da me per la lezione successiva e discusso insieme.</p><h2>Percorso</h2><p>Sono un ricercatore in economia, laureato in triennale e magistrale a Torino e con un master in ricerca ottenuto negli Stati Uniti. Durante il percorso all'estero ho insegnato, con ottimi risultati, a piu' di duecento studenti. Ho raggiunto un livello di conoscenza della lingua inglese pari a un C2 (livello europeo). Pertanto, offro ripetizioni di inglese per quanto riguarda la parte sia orale (speaking and listening) sia scritta (writing and reading).</p><h2><span style=\"background-color: rgb(247, 247, 247); color: rgb(68, 68, 68);\">&nbsp;</span>Tariffe</h2><p>Costo aggiuntivo per lo spostamento :&nbsp;<strong>5euro</strong></p><p>Tariffa per lezioni via webcam :&nbsp;<strong>15euro/ora</strong></p><p>Tariffa per un pacchetto di 5 ore di lezioni :&nbsp;<strong>70euro</strong></p><p>Tariffa per un pacchetto di 10 ore di lezioni :&nbsp;<strong>130euro</strong></p><h2><span style=\"background-color: rgb(247, 247, 247); color: rgb(68, 68, 68);\">&nbsp;</span><strong>Curriculum Vitae</strong>&nbsp;di Federico</h2><p>ESPERIENZA: ricercatore e docente presso la University of Wisconsin-Madison (USA), dal 08/2017 al 12/2019.</p><p><br></p><p>FORMAZIONE:</p><p>2019: Master in Research in Economics presso la University of Wisconsin-Madison (USA)</p><p>2017: Magistrale in Economics, Torino (110/110 con lode)</p><p>2014: Triennale in Economia e Commercio, Torino (110/110 con lode)</p>"),
    
    ("Ahmad", "TooLong", NULL, "1995-01-30", "dontknow@live.it", SHA2("Lol16153",256), "3333333336", "London", "<h1>Ricercatore in Economia, ho vissuto negli Stati Uniti negli ultimi 3 anni. Offro ripetizioni di inglese (speaking, listening, writing and reading)</h1><h2>Metodologia</h2><p>Le lezioni sono fortemente basate sulle necessita' dello studente. A seconda delle sue preferenze e dei suoi desideri, possiamo lavorare intensamente ogni lezione su un aspetto diverso della lingua (comprensione orale, comprensione scritta, elaborazione orale) con l'impegno di svolgere un elaborato scritto nelle pause tra una lezione e l'altra che potra'&nbsp; essere corretto da me per la lezione successiva e discusso insieme.</p><h2>Percorso</h2><p>Sono un ricercatore in economia, laureato in triennale e magistrale a Torino e con un master in ricerca ottenuto negli Stati Uniti. Durante il percorso all'estero ho insegnato, con ottimi risultati, a piu' di duecento studenti. Ho raggiunto un livello di conoscenza della lingua inglese pari a un C2 (livello europeo). Pertanto, offro ripetizioni di inglese per quanto riguarda la parte sia orale (speaking and listening) sia scritta (writing and reading).</p><h2><span style=\"background-color: rgb(247, 247, 247); color: rgb(68, 68, 68);\">&nbsp;</span>Tariffe</h2><p>Costo aggiuntivo per lo spostamento :&nbsp;<strong>5euro</strong></p><p>Tariffa per lezioni via webcam :&nbsp;<strong>15euro/ora</strong></p><p>Tariffa per un pacchetto di 5 ore di lezioni :&nbsp;<strong>70euro</strong></p><p>Tariffa per un pacchetto di 10 ore di lezioni :&nbsp;<strong>130euro</strong></p><h2><span style=\"background-color: rgb(247, 247, 247); color: rgb(68, 68, 68);\">&nbsp;</span><strong>Curriculum Vitae</strong>&nbsp;di Federico</h2><p>ESPERIENZA: ricercatore e docente presso la University of Wisconsin-Madison (USA), dal 08/2017 al 12/2019.</p><p><br></p><p>FORMAZIONE:</p><p>2019: Master in Research in Economics presso la University of Wisconsin-Madison (USA)</p><p>2017: Magistrale in Economics, Torino (110/110 con lode)</p><p>2014: Triennale in Economia e Commercio, Torino (110/110 con lode)</p>"), 
    
    ("Memen", "Change", "F", NULL, "whoknows@live.it", SHA2("WantPass123",256), NULL, "Paris", "<h1>Lezioni TELEMATICHE e TUTORING ONLINE di MATEMATICA, INFORMATICA e METODOLOGIA DELLO STUDIO per ragazzi e adulti, di qualsiasi livello. Appassionato di didattica con 10 ANNI DI ESPERIENZA.</h1><h2>Metodologia</h2><p><br></p><p>Mia metodologia consiste in adattare il insegnamento guardando le caratteristiche particolari di ogni studente e le sue capacita'&nbsp; di apprendimento.</p><p>Sempre utilizzo i libri proposti dei docenti e mi servo anche di altri materiali bibliografici che consegno di volta in volta.</p><h2>Ambasciatore</h2><p>E' il meglio del meglio degli insegnanti. Qualita'&nbsp; del profilo, diplomi e certificati di ottimo livello, risposta rapida. Marco preparera'&nbsp; con cura la prima lezione.</p><h2>Percorso</h2><p>Sono un Laureato in Informatica con 6 anni di Ing. Elettronica con 10 anni di esperienza nell'insegnamento della matematica e della informatica con un Master in Educazione ottenuto all'Universita'&nbsp; di Bologna, Facolta'&nbsp; di Scienze della Formazione e un master in Economia.</p><p><br></p><p>Normalmente miei studenti raggiungono ottimi risultati, tra cui voti dal 8 e 1/2 al 9 o esami di Matematica e informatica con valutazione 30/30.</p><p><br></p><p>Ho una grande passione per l'insegnamento e mi piace facilitare l'apprendimento dei miei allievi.</p><p><br></p><p>La laurea in INFORMATICA, i 6 anni di ING. ELETTRONICA e il MASTER in ECONOMIA sono le basi sulla quale ho sviluppato le conoscenze per l'insegnamento delle materie che rendo sempre comprensibili e alla portata di tutti!</p><p><br></p><p>Il MASTER IN EDUCAZIONE svolto mi permette di favorire lo sviluppo delle conoscenze dello studente con semplicita'&nbsp; e professionalita'&nbsp;.</p><h2>Tariffe</h2><p>Tariffa per lezioni via webcam :&nbsp;<strong>10euro/ora</strong></p><p>Tariffa per un pacchetto di 5 ore di lezioni :&nbsp;<strong>50euro</strong></p><p>Tariffa per un pacchetto di 10 ore di lezioni :&nbsp;<strong>100euro</strong></p><h2>Precisazioni</h2><p>Attualmente per venire incontro alle famiglia faccio euro 10 l'ora. Il prezzo reale dell'ora di Euro 20. La lezione si paga come minimo con 24 ore di anticipo. Un cambio d'orario o cancellazione della lezione con meno di 24 ore di anticipo se paga ugualmente perche' no faccio in tempo ad assegnare la lezione ad altri studenti!</p><p>Il prezzo della lezione varia in funzione del tempo disponibile e della complessita'&nbsp; degli argomenti richiesti.</p><p>Le lezioni se realizzano nel minor tempo possibile in relazione all'agenda normalmente entro 2 o 3 giorni.</p>");

-- ADD THE QUOTES THAT JQUILL NATUALLY INTRODUCES
UPDATE person SET Description=CONCAT('"',Description,'"');

-- TOPIC
INSERT INTO topic VALUES (NULL, "3D animation"), (NULL, "Computer networks"), (NULL, "Network security"), (NULL, "Web applications"), (NULL, "Calculus"), (NULL, "Physiscs"), (NULL, "Automation"), (NULL, "Machine Learning"), (NULL, "Operating systems"), (NULL, "Databases");
INSERT INTO topic VALUES (NULL, "Big Data Computing"), (NULL, "Computer Vision"), (NULL, "Distributed Systems"), (NULL, "Photoshop"), (NULL, "C"), (NULL, "C++"), (NULL, "Java"), (NULL, "JavaScript"), (NULL, "Python"), (NULL, "PHP");
INSERT INTO topic VALUES (NULL, "JSP"), (NULL, "Ruby"), (NULL, "Perl"), (NULL, "CSS"), (NULL, "HTML"), (NULL, "C#"), (NULL, "Arduino"), (NULL, "WordPress"), (NULL, "MySQL"), (NULL, "PostgreSQL");

-- TEACHER_TOPIC
-- ALL OF US AS MYSQL TEACHERS
INSERT INTO teacher_topic VALUES (1, 29, 13),(2, 29, 14),(3, 29, 12),(4, 29, 10),(5, 29, 16),(6, 29, 12), (4, 25, 10), (4, 24, 10), (4, 21, 10), (6, 30, 20), (3, 8, 30);



-- LESSON
INSERT INTO
    lesson(TeacherID, StudentID, LessonDate, LessonTime, LessonDuration, LessonTariff, Payment)
VALUES
    (1, 4, '2020-05-15', '08:30', '2:00', 16, '2020-05-13 23:59:59'),
    (2, 3, '2020-05-30', '12:00', '1:00', 18, '2020-05-28 23:59:59'),
    (2, 4, '2020-05-15', '08:30', '2:00', 14, '2020-05-13 23:59:59'),
    (1, 5, '2020-06-02', '11:00', '0:30', 15, '2020-05-30 23:59:59'),
    (2, 1, '2020-06-12', '08:30', '2:00', 13, '2020-06-10 23:59:59'),
    (3, 6, '2020-06-20', '14:00', '2:30', 16, '2020-06-18 23:59:59');
	
	
INSERT INTO
	feedback
VALUES
	(2, 3, 4, "Very good", '2020-05-13'),
	(2, 1, 4, "Excellent", '2020-05-13'),
	(2, 4, 5, "If you need a prepared, reliable, communicative and helpful person, contact him, you won't be disappointed", '2020-05-13'),
	(1, 3, 4, "Precise and helpful, recommended :)", '2020-05-13'),
	(4, 1, 4, "Patient and prepared", '2020-05-13'),
    (4, 2, 1, "Patient and prepared2", '2020-05-13'),	
	(4, 3, 3, "Patient and prepared3", '2020-05-13'),	
	(4, 5, 5, "Patient and prepared4", '2020-05-13');	


-- CHAT
INSERT INTO
    chat (TeacherID, StudentID, Confirmed, Messages, LastMessage) 
VALUES
    (2, 1, TRUE, '[{"SenderID": 2, "ReceiverID": 1, "Message": "hello there!", "TS": "2020-01-01 10:10:10"}]',  '2020-01-01 10:10:10'),
    (2, 3, TRUE, '[{"SenderID": 2, "ReceiverID": 3, "Message": "whats up!!", "TS": "2020-01-01 10:10:10"},{"SenderID": 3, "ReceiverID": 2, "Message": "Lorem ipsum dolor sit amet", "TS": "2020-01-01 10:10:10"}]',  '2020-01-01 10:10:10'),
    (3, 1, TRUE, '[{"SenderID": 3, "ReceiverID": 1, "Message": "Lorem ipsum dolor sit amet", "TS": "2020-01-01 10:10:10"}, {"SenderID": 1, "ReceiverID": 3, "Message": "consectetur adipiscing elit", "TS": "2020-01-01 10:10:10"}]',  '2020-01-01 10:10:10'),
    (2, 4, TRUE, '[{"SenderID": 2, "ReceiverID": 4, "Message": "Maecenas sit amet pretium urna", "TS": "2020-01-01 10:10:10"}, {"SenderID": 4, "ReceiverID": 2, "Message": "Lorem ipsum dolor sit amet", "TS": "2020-01-01 10:10:10"} ]',  '2020-01-01 10:10:10');
	